Repository clue/reactphp-soap, pull requests merged in 2020-10, with the labels that each got.

#44 Run tests on PHPUnit 9 and update PHPUnit configuration schema for PHPUnit 9.3
  .gitattributes
  .travis.yml
  composer.json
  phpunit.xml.dist
  phpunit.xml.legacy
  tests/FunctionalTest.php
  tests/Protocol/ClientDecoderTest.php
Labels: maintenance

#45 Update to reactphp/http v1.0.0
  README.md
  composer.json
  examples/01-client-blz-wsdl.php
  examples/02-client-blz-non-wsdl.php
  examples/11-wsdl-info.php
  src/Client.php
  src/Protocol/ClientEncoder.php
  tests/ClientTest.php
  tests/FunctionalTest.php
Labels: BC break, new feature

#46 Use fully qualified class names in documentation
  README.md
  src/Client.php
  src/Proxy.php
Labels: maintenance

#47 Drop support for HHVM, PHP 5, PHPUnit 4 and PHPUnit 5
  .travis.yml
  README.md
  composer.json
  phpunit.xml.legacy
Labels: BC break, maintenance

#48 Fix failing tests when ext-xdebug is not loaded and simplify tests for new Xdebug and PHPUnit versions
  README.md
  src/Client.php
  tests/ClientTest.php
  tests/FunctionalTest.php
  tests/Protocol/ClientDecoderTest.php
  tests/Protocol/ClientEncoderTest.php
Labels: bug, maintenance

#49 Add type declarations and require PHP 7.1+ as a consequence
  .travis.yml
  README.md
  composer.json
  phpunit.xml.legacy
  src/Client.php
  src/Protocol/ClientDecoder.php
  src/Protocol/ClientEncoder.php
  src/Proxy.php
  tests/FunctionalTest.php
Labels: BC break, new feature

#50 Prepare v2.0.0 release
  CHANGELOG.md
  README.md
  composer.json
  src/Client.php
Labels: maintenance
